postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: webapp
    POSTGRES_PASSWORD: pass
  ports:
    - '5432:5432'
  volumes:
    - '~/.docker-volumes/webapp/postgresql/data:/var/lib/postgresql/data'
redis:
  image: redis:2.8.22
  ports:
    - '6379:6379'
  volumes:
    - ~/.docker-volumes/webapp/redis/data:/var/lib/redis/data

webapp:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/webapp
  ports:
    - '8000:8000'
  env_file:
    - .webapp.env
